CREATE DATABASE QUANLYSACH

GO

USE QUANLYSACH

GO



CREATE FUNCTION AUTO_MATG()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @TACGIA CHAR(5)
	IF(SELECT COUNT(MATG) FROM TACGIA) = 0
		SET @TACGIA = '0'
	ELSE
		SELECT @TACGIA = MAX(RIGHT(MATG,3)) FROM TACGIA
		SELECT @TACGIA = CASE 
			WHEN @TACGIA >= 0 and @TACGIA < 9 THEN 'TG00' + CONVERT(CHAR, CONVERT(INT, @TACGIA) + 1)
			WHEN @TACGIA >= 9 and @TACGIA < 99 THEN 'TG0' + CONVERT(CHAR, CONVERT(INT, @TACGIA) + 1)
			WHEN @TACGIA >= 99 THEN 'TG' + CONVERT(CHAR, CONVERT(INT, @TACGIA) + 1)
	END
	RETURN @TACGIA
END

GO

CREATE TABLE TACGIA
(
	MATG CHAR(5) PRIMARY KEY DEFAULT dbo.AUTO_MATG(), -- TG001
	TENTG NVARCHAR(50),
	DIACHI NVARCHAR(100),
)

GO

CREATE FUNCTION AUTO_MATL()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MATL CHAR(5)
	IF(SELECT COUNT(MATL) FROM THELOAI) = 0
		SET @MATL = '0'
	ELSE
		SELECT @MATL = MAX(RIGHT(MATL,3)) FROM THELOAI
		SELECT @MATL = CASE 
			WHEN @MATL >= 0 and @MATL < 9 THEN 'TL00' + CONVERT(CHAR, CONVERT(INT, @MATL) + 1)
			WHEN @MATL >= 9 and @MATL < 99 THEN 'TL0' + CONVERT(CHAR, CONVERT(INT, @MATL) + 1)
			WHEN @MATL >= 99 THEN 'TL' + CONVERT(CHAR, CONVERT(INT, @MATL) + 1)
	END
	RETURN @MATL
END

GO

CREATE TABLE THELOAI
(
	MATL CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_MATL(), -- TL001
	TENTL NVARCHAR(50)
)

GO



CREATE FUNCTION AUTO_MANXB()
RETURNS CHAR(6)
AS
BEGIN
	DECLARE @MANXB CHAR(6)
	IF(SELECT COUNT(MANXB) FROM NHAXUATBAN) = 0
		SET @MANXB = '0'
	ELSE
		SELECT @MANXB = MAX(RIGHT(MANXB,3)) FROM NHAXUATBAN
		SELECT @MANXB = CASE 
			WHEN @MANXB >= 0 and @MANXB < 9 THEN 'NXB00' + CONVERT(CHAR, CONVERT(INT, @MANXB) + 1)
			WHEN @MANXB >= 9 and @MANXB < 99 THEN 'NXB0' + CONVERT(CHAR, CONVERT(INT, @MANXB) + 1)
			WHEN @MANXB >= 99 THEN 'NXB' + CONVERT(CHAR, CONVERT(INT, @MANXB) + 1)
	END
	RETURN @MANXB
END

GO

CREATE TABLE NHAXUATBAN
(
	MANXB CHAR(6) PRIMARY KEY DEFAULT DBO.AUTO_MANXB(), --NXB001
	TENNXB NVARCHAR(50),
	DIACHINXB NVARCHAR(100),
	DIENTHOAI CHAR(20)
)

GO

CREATE FUNCTION AUTO_MASACH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MASACH CHAR(5)
	IF(SELECT COUNT(MASACH) FROM SACH) = 0
		SET @MASACH = '0'
	ELSE
		SELECT @MASACH = MAX(RIGHT(MASACH,3)) FROM SACH
		SELECT @MASACH = CASE 
			WHEN @MASACH >= 0 and @MASACH < 9 THEN 'SA00' + CONVERT(CHAR, CONVERT(INT, @MASACH) + 1)
			WHEN @MASACH >= 9 and @MASACH < 99 THEN 'SA0' + CONVERT(CHAR, CONVERT(INT, @MASACH) + 1)
			WHEN @MASACH >= 99 THEN 'SA' + CONVERT(CHAR, CONVERT(INT, @MASACH) + 1)
	END
	RETURN @MASACH
END

GO

CREATE TABLE SACH
(
	MASACH CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_MASACH(), --SA001
	TENSACH NVARCHAR(50),
	MATL CHAR(5),
	MANXB CHAR(6),
	MATG CHAR(5),
	SLTON INT,
	DONGIA INT CHECK (DONGIA > 0),
	CONSTRAINT FK_SACH_TL FOREIGN KEY (MATL) REFERENCES THELOAI(MATL),
	CONSTRAINT FK_SACH_NHAXUATBAN FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN(MANXB),
	CONSTRAINT FK_SACH_TACGIA FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)
)

GO

CREATE FUNCTION AUTO_MANG()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MANG CHAR(5)
	IF(SELECT COUNT(MANG) FROM NGUOIDUNG) = 0
		SET @MANG = '0'
	ELSE
		SELECT @MANG = MAX(RIGHT(MANG,3)) FROM NGUOIDUNG
		SELECT @MANG = CASE 
			WHEN @MANG >= 0 and @MANG < 9 THEN 'NG00' + CONVERT(CHAR, CONVERT(INT, @MANG) + 1)
			WHEN @MANG >= 9 and @MANG < 99 THEN 'NG0' + CONVERT(CHAR, CONVERT(INT, @MANG) + 1)
			WHEN @MANG >= 99 THEN 'NG' + CONVERT(CHAR, CONVERT(INT, @MANG) + 1)
	END
	RETURN @MANG
END

GO

CREATE TABLE NGUOIDUNG
(
	MANG CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_MANG(), --NG001
	TEN NVARCHAR(50),
	GIOITINH NVARCHAR (5),
	MATKHAU CHAR(50) DEFAULT 1,
	SDT CHAR(20),
	NGAYSINH DATE,
	LOAI INT, --0: QUANLY 1:NHANVIEN 
)

GO

CREATE FUNCTION AUTO_MAKH()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MAKH CHAR(5)
	IF(SELECT COUNT(MAKH) FROM KHACHHANG) = 0
		SET @MAKH = '0'
	ELSE
		SELECT @MAKH = MAX(RIGHT(MAKH,3)) FROM KHACHHANG
		SELECT @MAKH = CASE 
			WHEN @MAKH >= 0 and @MAKH < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @MAKH) + 1)
			WHEN @MAKH >= 9 and @MAKH < 99 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @MAKH) + 1)
			WHEN @MAKH >= 99 THEN 'KH' + CONVERT(CHAR, CONVERT(INT, @MAKH) + 1)
	END
	RETURN @MAKH
END

GO


CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_MAKH(), --KH001
	TEN NVARCHAR(50),
	GIOITINH NVARCHAR(5),
	MATKHAU CHAR(50) DEFAULT 1,
	SDT CHAR(20),
	NGAYSINH DATE
)

GO
CREATE TABLE USERS
(
	MAKH CHAR(5) PRIMARY KEY,
	TEN NVARCHAR(50)
)

GO

CREATE FUNCTION AUTO_SOPN()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @SOPN CHAR(5)
	IF(SELECT COUNT(SOPN) FROM PHIEUNHAP) = 0
		SET @SOPN = '0'
	ELSE
		SELECT @SOPN = MAX(RIGHT(SOPN,3)) FROM PHIEUNHAP
		SELECT @SOPN = CASE 
			WHEN @SOPN >= 0 and @SOPN < 9 THEN 'PN00' + CONVERT(CHAR, CONVERT(INT, @SOPN) + 1)
			WHEN @SOPN >= 9 and @SOPN < 99 THEN 'PN0' + CONVERT(CHAR, CONVERT(INT, @SOPN) + 1)
			WHEN @SOPN >= 99 THEN 'PN' + CONVERT(CHAR, CONVERT(INT, @SOPN) + 1)
	END
	RETURN @SOPN
END

GO

CREATE TABLE PHIEUNHAP
(
	SOPN CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_SOPN(), --PN001
	NGAYNHAP DATE CHECK (NGAYNHAP <= GETDATE()),
	MANG CHAR(5),
	CONSTRAINT FK_PHIEUNHAP_NGUOIDUNG FOREIGN KEY (MANG) REFERENCES NGUOIDUNG(MANG)
)

GO

CREATE FUNCTION AUTO_MAPHIEUDAT()
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @MAPHIEUDAT CHAR(5)
	IF(SELECT COUNT(MAPHIEUDAT) FROM PHIEUDATSACH) = 0
		SET @MAPHIEUDAT = '0'
	ELSE
		SELECT @MAPHIEUDAT = MAX(RIGHT(MAPHIEUDAT,3)) FROM PHIEUDATSACH
		SELECT @MAPHIEUDAT = CASE 
			WHEN @MAPHIEUDAT >= 0 and @MAPHIEUDAT < 9 THEN 'PD00' + CONVERT(CHAR, CONVERT(INT, @MAPHIEUDAT) + 1)
			WHEN @MAPHIEUDAT >= 9 and @MAPHIEUDAT < 99 THEN 'PD0' + CONVERT(CHAR, CONVERT(INT, @MAPHIEUDAT) + 1)
			WHEN @MAPHIEUDAT >= 99 THEN 'PD' + CONVERT(CHAR, CONVERT(INT, @MAPHIEUDAT) + 1)
	END
	RETURN @MAPHIEUDAT
END

GO

CREATE TABLE PHIEUDATSACH
(
	MAPHIEUDAT CHAR(5) PRIMARY KEY DEFAULT DBO.AUTO_MAPHIEUDAT(), --PD001
	MAKH CHAR(5),
	MANG CHAR(5),
	NGAYDAT DATE,
	NGAYBAN DATE,
	TRANGTHAI CHAR(10) DEFAULT 'CHUATINH',
	TONGTIEN INT DEFAULT 0,
	CONSTRAINT FK_PHIEUDATSACH_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_PHIEUDATSACH_NGUOIDUNG FOREIGN KEY (MANG) REFERENCES NGUOIDUNG(MANG),
	CONSTRAINT CHK_NGAYBAN CHECK(NGAYBAN >= NGAYDAT)
)

GO

CREATE TABLE CHITIETPHIEUDATSACH
(
	MAPHIEUDAT CHAR(5),
	MASACH CHAR(5),
	SOLUONG INT CHECK (SOLUONG > 0),
	PRIMARY KEY (MAPHIEUDAT, MASACH),
	CONSTRAINT FK_CHITIETPHIEUDATSACH_KHACHHANG FOREIGN KEY (MAPHIEUDAT) REFERENCES PHIEUDATSACH(MAPHIEUDAT),
	CONSTRAINT FK_CHITIETPHIEUDATSACH_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)

GO



CREATE TABLE CHITIETPHIEUNHAP
(
	SOPN CHAR(5),
	MASACH CHAR(5),
	SLNHAP INT CHECK (SLNHAP > 0),
	GIANHAP INT CHECK (GIANHAP > 0),
	PRIMARY KEY (SOPN,MASACH),
	CONSTRAINT FK_CHITIETPHIEUNHAP_PHIEUNHAP FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
	CONSTRAINT FK_CHITIETPHIEUNHAP_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
)



INSERT INTO TACGIA(TENTG,DIACHI) VALUES (N'Nguyễn Văn A',N'Quận 7, Hồ Chí Minh')
INSERT INTO TACGIA(TENTG,DIACHI) VALUES (N'Nguyễn Văn B',N'Tiền Giang')
INSERT INTO TACGIA(TENTG,DIACHI) VALUES (N'Huỳnh Thị C',N'An Giang')

INSERT INTO THELOAI(TENTL) VALUES(N'Văn hóa')
INSERT INTO THELOAI(TENTL) VALUES(N'Du lịch')
INSERT INTO THELOAI(TENTL) VALUES(N'Chính trị')

INSERT INTO NHAXUATBAN(TENNXB,DIACHINXB,DIENTHOAI) VALUES (N'Nhà xuất bản Văn Hóa',N'Hồ Chí Minh','0123456789')
INSERT INTO NHAXUATBAN(TENNXB,DIACHINXB,DIENTHOAI) VALUES (N'Nhà xuất bản Du Lịch',N'Hồ Chí Minh','0909333123')
INSERT INTO NHAXUATBAN(TENNXB,DIACHINXB,DIENTHOAI) VALUES (N'Nhà xuất bản Chính Trị',N'Hà Nội','098255677')

INSERT INTO SACH(TENSACH,MATL,MANXB,MATG,SLTON,DONGIA) VALUES(N'Sách văn hóa','TL001','NXB001','TG001',100,80000)
INSERT INTO SACH(TENSACH,MATL,MANXB,MATG,SLTON,DONGIA) VALUES(N'Sách du lịch','TL002','NXB002','TG002',100,90000)
INSERT INTO SACH(TENSACH,MATL,MANXB,MATG,SLTON,DONGIA) VALUES(N'Sách chính trị','TL003','NXB003','TG003',100,100000)

INSERT INTO NGUOIDUNG(TEN,GIOITINH,MATKHAU,SDT,NGAYSINH,LOAI) VALUES(N'Huỳnh Bông',N'Nữ','1','0123456789','01/01/1997',1)
INSERT INTO NGUOIDUNG(TEN,GIOITINH,MATKHAU,SDT,NGAYSINH,LOAI) VALUES(N'Admin',N'Nam','1','0123456789','01/01/1997',0)
INSERT INTO NGUOIDUNG(TEN,GIOITINH,MATKHAU,SDT,NGAYSINH,LOAI) VALUES(N'HP',N'Nam','1','0907334138','05/17/1996',1)

INSERT INTO KHACHHANG(TEN,GIOITINH,MATKHAU,SDT,NGAYSINH) VALUES(N'Nguyễn La',N'Nam','1','0123987453','01/01/1997')

INSERT INTO PHIEUNHAP(NGAYNHAP,MANG) VALUES ('07/22/2018','NG001')

INSERT INTO CHITIETPHIEUNHAP (SOPN,MASACH,SLNHAP,GIANHAP) VALUES('PN001','SA001',100,60000)
INSERT INTO CHITIETPHIEUNHAP (SOPN,MASACH,SLNHAP,GIANHAP) VALUES('PN001','SA002',100,70000)

INSERT INTO PHIEUDATSACH(MAKH,NGAYDAT) VALUES ('KH001','07/25/2018')

INSERT INTO CHITIETPHIEUDATSACH(MAPHIEUDAT,MASACH,SOLUONG) VALUES ('PD001','SA001',2)
INSERT INTO CHITIETPHIEUDATSACH(MAPHIEUDAT,MASACH,SOLUONG) VALUES ('PD001','SA002',3)




select MANG as N'Mã nhân viên', TEN as N'Tên', GIOITINH as N'Giới tính', MATKHAU as N'Mật khẩu', SDT as N'Số điện thoại', NGAYSINH as N'Ngày sinh', LOAI as N'Loại' from NGUOIDUNG

select MAKH from USERS

select * from PHIEUDATSACH

select * from NGUOIDUNG

select * from USERS
delete USERS

select * from KHACHHANG

select MANG from NGUOIDUNG where NGUOIDUNG.TEN = N'Admin'

select MAPHIEUDAT from PHIEUDATSACH
where PHIEUDATSACH.MAKH = 'KH001'
and PHIEUDATSACH.NGAYDAT = '07/25/2018'

select SACH.TENSACH, CHITIETPHIEUDATSACH.SOLUONG from CHITIETPHIEUDATSACH, SACH where CHITIETPHIEUDATSACH.MASACH = SACH.MASACH And CHITIETPHIEUDATSACH.MAPHIEUDAT = 'PD001'

select * from PHIEUDATSACH
select * from CHITIETPHIEUDATSACH

delete CHITIETPHIEUDATSACH
where MAPHIEUDAT = 'PD002'

select SLTON
from SACH
where MASACH = 'SA001'

select SLTON from SACH 

delete PHIEUDATSACH

select SACH.TENSACH, CHITIETPHIEUDATSACH.SOLUONG from CHITIETPHIEUDATSACH, SACH where CHITIETPHIEUDATSACH.MASACH = SACH.MASACH 
And CHITIETPHIEUDATSACH.MAPHIEUDAT ='PD017'

select SOLUONG  from CHITIETPHIEUDATSACH where MAPHIEUDAT = 'PD010' and MASACH = 'SA001'

update CHITIETPHIEUDATSACH set SOLUONG = 1 where MAPHIEUDAT = '' and MASACH = ''

SELECT CHITIETPHIEUDATSACH.MAPHIEUDAT, SACH.TENSACH,CHITIETPHIEUDATSACH.SOLUONG,SACH.DONGIA, (CHITIETPHIEUDATSACH.SOLUONG * SACH.DONGIA) AS 'THANHTIEN'
FROM SACH,CHITIETPHIEUDATSACH
WHERE SACH.MASACH = CHITIETPHIEUDATSACH.MASACH
and CHITIETPHIEUDATSACH.MAPHIEUDAT = 'PD002'

update SACH set SLTON = 1 where MASACH = '' 

select SLTON from SACH where MASACH = ''

select * from PHIEUDATSACH

update PHIEUDATSACH set TONGTIEN = 0 where MAPHIEUDAT = 'PD001'

select Distinct MAPHIEUDAT, KHACHHANG.TEN as 'TENKH',NGAYDAT,NGAYBAN,TRANGTHAI,TONGTIEN
from KHACHHANG,PHIEUDATSACH
where PHIEUDATSACH.MAKH = KHACHHANG.MAKH
and TRANGTHAI = 'CHUATINH'

select Distinct * from PHIEUDATSACH

update PHIEUDATSACH
set MANG = 'NG001', NGAYBAN = '09/14/2018', TRANGTHAI ='DATINH'
where MAPHIEUDAT = 'PD001'

select * from PHIEUDATSACH

select *  from PHIEUDATSACH 
where MAPHIEUDAT = 'PD001'

